#ifndef _LIB_DRAMALIFE_DATA_STRUCT_LIB_H_
#define _LIB_DRAMALIFE_DATA_STRUCT_LIB_H_

#define DATA_STRUCT_LINK_LIST_VERSION_3_0_0	0x003000000
#define DATA_STRUCT_LINK_LIST_VERSION_4_19_38	0x004019038

/*****
 * Configuration
 * Select Link list version
 */
#ifndef DATA_STRUCT_LINK_LIST_VERSION
#define DATA_STRUCT_LINK_LIST_VERSION	DATA_STRUCT_LINK_LIST_VERSION_3_0_0
#endif


#if DATA_STRUCT_LINK_LIST_VERSION == DATA_STRUCT_LINK_LIST_VERSION_3_0_0
#include "./list30.h"
#elif DATA_STRUCT_LINK_LIST_VERSION == DATA_STRUCT_LINK_LIST_VERSION_4_19_38
#include "./list-4.19.38.h"
#endif

#endif
