PATH_ABS=../../../../lib_dramalife/
#DEF_MACROS +="-D PROVIDE_MAIN_FUNCTION_IN_LIB=1"
DEF_MACROS +="-D PROVIDE_START_FUNCTION_IN_LIB=1"
DEF_MACROS +="-D DESIGNATE_LD_IN_LIB_FILE=1"
CFLAGS+=-fPIC -shared

DO_NOT_SET_DEFAULT_BINARY_NAME=1
BIN_NAME=libbacktrace_funcs
BIN_DNAME=${SHD_LIB} 
