# note "source & export" related file
# Copyright (C) 2019 Dramalife@live.com
# 
# This file is part of [note](https://github.com/Dramalife/note.git)
# 
# note is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# bash --version
# TODO;
#
# Init : 2019.09.13;
# Update :
#


all:
	@echo ""
	@echo ""
	@echo "print from make.........."
	@echo "VAR____IN_SOURCE:"$(VAR_SC)
	@echo "EXPORT_IN_SOURCE:"$(EX_SC)
	@echo "VAR____IN_SHELL :"$(VAR_SH)
	@echo "EXPORT_IN_SHELL :"$(EX_SH)
	@echo "print end................."
	@echo ""
	@echo ""
